console.log("Hello");
console.log("helloworld");
console.log("helloworld");
console.log("helloworld");
console.log("helloworld");
console.log("helloworld");
console.log("helloworld");
console.log("helloworld");
console.log("helloworld");
console.log("helloworld");
console.log("helloworld");
console.log("helloworld");
console.log("wertyui")